"""Authorize local Gmail refresh tokens for personal-actions Gmail tools."""

from __future__ import annotations

import argparse
import json
import secrets
import subprocess
import sys
import threading
import urllib.parse
import urllib.request
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

SECRETS_DIR = Path.home() / ".config" / "agents-secrets"
OAUTH_ENV = SECRETS_DIR / "windmill-oauth.env"
PERSONAL_ENV = SECRETS_DIR / "personal-actions.env"
CAPABILITIES = {
    "compose": {
        "scope": "https://www.googleapis.com/auth/gmail.compose",
        "personal_port": 8765,
        "work_port": 8766,
        "env_kind": "COMPOSE",
        "label": "Gmail compose",
    },
    "modify": {
        "scope": "https://www.googleapis.com/auth/gmail.modify",
        "personal_port": 8767,
        "work_port": 8768,
        "env_kind": "MODIFY",
        "label": "Gmail modify",
    },
}


def load_env(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip().strip("'\"")
    return data


def write_env(path: Path, updates: dict[str, str]) -> None:
    data = load_env(path)
    data.update(updates)
    path.write_text(
        "# Generated by personal-actions tooling. Do not commit.\n"
        + "\n".join(f"{key}={value}" for key, value in data.items())
        + "\n",
        encoding="utf-8",
    )
    path.chmod(0o600)


class Callback(BaseHTTPRequestHandler):
    server: "CallbackServer"

    def do_GET(self) -> None:  # noqa: N802
        parsed = urllib.parse.urlparse(self.path)
        query = urllib.parse.parse_qs(parsed.query)
        self.server.code = query.get("code", [""])[0]
        self.server.state = query.get("state", [""])[0]
        self.send_response(200 if self.server.code else 400)
        self.end_headers()
        self.wfile.write(b"You can close this tab and return to the terminal.")

    def log_message(self, _format: str, *_args: object) -> None:
        return


class CallbackServer(HTTPServer):
    code = ""
    state = ""


def exchange_code(client_id: str, client_secret: str, code: str, redirect_uri: str) -> dict[str, str]:
    body = urllib.parse.urlencode(
        {
            "client_id": client_id,
            "client_secret": client_secret,
            "code": code,
            "redirect_uri": redirect_uri,
            "grant_type": "authorization_code",
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        "https://oauth2.googleapis.com/token",
        data=body,
        method="POST",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310
        return json.loads(resp.read().decode("utf-8", errors="replace"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--account", choices=["personal", "work"], default="personal")
    parser.add_argument("--capability", choices=sorted(CAPABILITIES), default="compose")
    parser.add_argument("--port", type=int)
    args = parser.parse_args()
    capability = CAPABILITIES[args.capability]
    port = args.port or int(capability["work_port"] if args.account == "work" else capability["personal_port"])
    oauth = load_env(OAUTH_ENV)
    client_id = oauth.get("GOOGLE_OAUTH_CLIENT_ID", "")
    client_secret = oauth.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
    if not client_id or not client_secret:
        print(f"missing GOOGLE_OAUTH_CLIENT_ID/SECRET in {OAUTH_ENV}", file=sys.stderr)
        return 1

    redirect_uri = f"http://127.0.0.1:{port}/callback"
    state = secrets.token_urlsafe(24)
    server = CallbackServer(("127.0.0.1", port), Callback)
    thread = threading.Thread(target=server.handle_request, daemon=True)
    thread.start()
    params = urllib.parse.urlencode(
        {
            "client_id": client_id,
            "redirect_uri": redirect_uri,
            "response_type": "code",
            "scope": capability["scope"],
            "access_type": "offline",
            "prompt": "consent",
            "state": state,
        }
    )
    url = f"https://accounts.google.com/o/oauth2/v2/auth?{params}"
    print(f"Opening Google OAuth for {args.account} {capability['label']}.")
    print(f"Add this redirect URI to the OAuth client first if needed: {redirect_uri}")
    subprocess.run(["open", url], check=False)
    thread.join(timeout=180)
    server.server_close()
    if not server.code or server.state != state:
        print("OAuth callback did not complete", file=sys.stderr)
        return 1
    token = exchange_code(client_id, client_secret, server.code, redirect_uri)
    refresh = str(token.get("refresh_token", "")).strip()
    if not refresh:
        print("Google did not return a refresh_token; revoke app access and retry with prompt=consent", file=sys.stderr)
        return 1
    env_kind = str(capability["env_kind"])
    prefix = f"PERSONAL_WORK_GMAIL_{env_kind}" if args.account == "work" else f"PERSONAL_GMAIL_{env_kind}"
    write_env(
        PERSONAL_ENV,
        {
            f"{prefix}_CLIENT_ID": client_id,
            f"{prefix}_CLIENT_SECRET": client_secret,
            f"{prefix}_REFRESH_TOKEN": refresh,
        },
    )
    print(f"Stored {args.account} {capability['label']} refresh token in {PERSONAL_ENV}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
