"""Bootstrap the local Windmill backend for personal-actions."""

from __future__ import annotations

import json
import os
import secrets
import string
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

BASE_URL = os.environ.get("WINDMILL_BASE_URL", "http://localhost:8790").rstrip("/")
WORKSPACE = os.environ.get("WINDMILL_WORKSPACE", "personal")
ADMIN_EMAIL = os.environ.get("WINDMILL_ADMIN_EMAIL", "admin@windmill.dev")
DEFAULT_PASSWORD = "changeme"
SCRIPT_PATH = "f/personal_actions/handler"
TRIGGER_PATH = "u/admin/personal_actions_route"
ROUTE_PATH = "personal-actions"
SECRETS_DIR = Path.home() / ".config" / "agents-secrets"
ADMIN_ENV = SECRETS_DIR / "windmill-admin.env"
PERSONAL_ENV = SECRETS_DIR / "personal-actions.env"
HANDLER = Path.home() / ".config" / "agents" / "assistant" / "windmill" / "personal_actions_handler.ts"


class ApiError(RuntimeError):
    pass


def random_password() -> str:
    alphabet = string.ascii_letters + string.digits + "-_"
    return "".join(secrets.choice(alphabet) for _ in range(36))


def load_env(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip().strip("'\"")
    return data


def write_admin_env(password: str) -> None:
    SECRETS_DIR.mkdir(parents=True, exist_ok=True)
    ADMIN_ENV.write_text(
        "\n".join(
            [
                "# Generated by windmill-bootstrap. Do not commit.",
                f"WINDMILL_BASE_URL={BASE_URL}",
                f"WINDMILL_ADMIN_EMAIL={ADMIN_EMAIL}",
                f"WINDMILL_ADMIN_PASSWORD={password}",
                f"WINDMILL_WORKSPACE={WORKSPACE}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    ADMIN_ENV.chmod(0o600)


def update_personal_env(url: str) -> None:
    data = load_env(PERSONAL_ENV)
    data.setdefault("PERSONAL_ACTIONS_PROVIDER", "webhook")
    data["PERSONAL_ACTIONS_WEBHOOK_URL"] = url
    data.setdefault("PERSONAL_ACTIONS_WEBHOOK_TOKEN", secrets.token_hex(32))
    data.setdefault("PERSONAL_ACTIONS_WEBHOOK_HMAC_SECRET", secrets.token_hex(32))
    data.setdefault("PERSONAL_ACTIONS_DRY_RUN", "1")
    data["PERSONAL_ACTIONS_ALLOW_HTTP"] = "1"
    SECRETS_DIR.mkdir(parents=True, exist_ok=True)
    PERSONAL_ENV.write_text(
        "# Generated by windmill-bootstrap/personal-actions-configure. Do not commit.\n"
        + "\n".join(f"{key}={value}" for key, value in data.items())
        + "\n",
        encoding="utf-8",
    )
    PERSONAL_ENV.chmod(0o600)


def request(method: str, path: str, token: str | None = None, body: object | None = None) -> tuple[int, str]:
    payload = None if body is None else json.dumps(body, separators=(",", ":")).encode("utf-8")
    req = urllib.request.Request(f"{BASE_URL}{path}", data=payload, method=method)
    if body is not None:
        req.add_header("Content-Type", "application/json")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310
            return resp.status, resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        text = exc.read().decode("utf-8", errors="replace")
        raise ApiError(f"{method} {path} failed: HTTP {exc.code}: {text}") from exc
    except urllib.error.URLError as exc:
        raise ApiError(f"{method} {path} failed: {exc.reason}") from exc


def login(password: str) -> str:
    _, text = request("POST", "/api/auth/login", body={"email": ADMIN_EMAIL, "password": password})
    return text.strip()


def auth_token() -> tuple[str, str]:
    stored = load_env(ADMIN_ENV).get("WINDMILL_ADMIN_PASSWORD", "")
    if stored:
        try:
            return login(stored), stored
        except ApiError:
            pass
    token = login(DEFAULT_PASSWORD)
    new_password = random_password()
    request("POST", "/api/users/setpassword", token, {"password": new_password})
    write_admin_env(new_password)
    return login(new_password), new_password


def path_quote(path: str) -> str:
    return urllib.parse.quote(path, safe="")


def exists(token: str, path: str) -> bool:
    try:
        _, text = request("GET", path, token)
        return text.strip().lower() == "true"
    except ApiError:
        return False


def ensure_workspace(token: str) -> None:
    _, text = request("GET", "/api/workspaces/list", token)
    workspaces = json.loads(text)
    if any(ws.get("id") == WORKSPACE for ws in workspaces):
        return
    request(
        "POST",
        "/api/workspaces/create",
        token,
        {"id": WORKSPACE, "name": "Personal Actions", "color": "#3b82f6"},
    )


def ensure_variable(token: str, path: str, value: str, description: str) -> None:
    body = {"path": path, "value": value, "is_secret": True, "description": description}
    if exists(token, f"/api/w/{WORKSPACE}/variables/exists/{path_quote(path)}"):
        request("POST", f"/api/w/{WORKSPACE}/variables/update/{path_quote(path)}", token, body)
    else:
        request("POST", f"/api/w/{WORKSPACE}/variables/create", token, body)


def ensure_script(token: str) -> None:
    content = HANDLER.read_text(encoding="utf-8") + f"\n// deployed_at={int(time.time())}\n"
    if exists(token, f"/api/w/{WORKSPACE}/scripts/exists/p/{path_quote(SCRIPT_PATH)}"):
        request("POST", f"/api/w/{WORKSPACE}/scripts/archive/p/{path_quote(SCRIPT_PATH)}", token)
    request(
        "POST",
        f"/api/w/{WORKSPACE}/scripts/create",
        token,
        {
            "path": SCRIPT_PATH,
            "summary": "Personal actions webhook handler",
            "description": "Validates and dispatches the shared personal-actions MCP webhook.",
            "content": content,
            "language": "deno",
            "kind": "script",
            "tag": "deno",
            "deployment_message": "Bootstrap personal actions handler",
        },
    )


def script_hash(token: str) -> str:
    _, text = request("GET", f"/api/w/{WORKSPACE}/scripts/get/p/{SCRIPT_PATH}", token)
    return json.loads(text)["hash"]


def create_run_token(token: str) -> str:
    scope = f"jobs:run:scripts:{SCRIPT_PATH}"
    try:
        _, text = request(
            "POST",
            "/api/users/tokens/create",
            token,
            {
                "label": "personal-actions-windmill-webhook",
                "workspace_id": WORKSPACE,
                "scopes": [scope],
            },
        )
        return text.strip()
    except ApiError:
        return token


def ensure_trigger(token: str) -> str:
    body = {
        "path": TRIGGER_PATH,
        "script_path": SCRIPT_PATH,
        "route_path": ROUTE_PATH,
        "workspaced_route": False,
        "summary": "Personal actions webhook",
        "description": "Local webhook for Slack/Gmail/Calendar personal actions.",
        "is_flow": False,
        "http_method": "post",
        "authentication_method": "none",
        "is_static_website": False,
        "request_type": "sync",
        "wrap_body": False,
        "raw_string": True,
    }
    if exists(token, f"/api/w/{WORKSPACE}/http_triggers/exists/{path_quote(TRIGGER_PATH)}"):
        request("POST", f"/api/w/{WORKSPACE}/http_triggers/update/{path_quote(TRIGGER_PATH)}", token, body)
    else:
        request("POST", f"/api/w/{WORKSPACE}/http_triggers/create", token, body)
    return f"{BASE_URL}/api/r/{ROUTE_PATH}"


def main() -> int:
    token, _password = auth_token()
    ensure_workspace(token)
    env = load_env(PERSONAL_ENV)
    webhook_token = env.get("PERSONAL_ACTIONS_WEBHOOK_TOKEN") or secrets.token_hex(32)
    hmac_secret = env.get("PERSONAL_ACTIONS_WEBHOOK_HMAC_SECRET") or secrets.token_hex(32)
    ensure_variable(token, "u/admin/personal_actions_webhook_token", webhook_token, "Bearer token for personal actions")
    ensure_variable(token, "u/admin/personal_actions_hmac_secret", hmac_secret, "HMAC secret for personal actions")
    ensure_script(token)
    script_webhook_url = f"{BASE_URL}/api/w/{WORKSPACE}/jobs/run_wait_result/h/{script_hash(token)}"
    ensure_trigger(token)
    update_personal_env(script_webhook_url)
    env = load_env(PERSONAL_ENV)
    env["PERSONAL_ACTIONS_WEBHOOK_TOKEN"] = create_run_token(token)
    PERSONAL_ENV.write_text(
        "# Generated by windmill-bootstrap/personal-actions-configure. Do not commit.\n"
        + "\n".join(f"{key}={value}" for key, value in env.items())
        + "\n",
        encoding="utf-8",
    )
    PERSONAL_ENV.chmod(0o600)
    print(f"Windmill workspace: {WORKSPACE}")
    print(f"Personal actions webhook: {script_webhook_url}")
    print(f"Admin credentials: {ADMIN_ENV}")
    print(f"Personal actions env: {PERSONAL_ENV}")
    print("Dry-run remains enabled; set PERSONAL_ACTIONS_DRY_RUN=0 after OAuth resources are connected.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ApiError as exc:
        print(f"windmill-bootstrap: {exc}", file=sys.stderr)
        raise SystemExit(1)
